#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqRepositorySample
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wf_meddemo")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertwfdc_FDB_RMIID1_MED(wfdc_FDB_RMIID1_MED instance);
    partial void Updatewfdc_FDB_RMIID1_MED(wfdc_FDB_RMIID1_MED instance);
    partial void Deletewfdc_FDB_RMIID1_MED(wfdc_FDB_RMIID1_MED instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LinqRepositorySample.Properties.Settings.Default.wf_meddemoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<wfdc_FDB_RMIID1_MED> wfdc_FDB_RMIID1_MEDs
		{
			get
			{
				return this.GetTable<wfdc_FDB_RMIID1_MED>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wfdc_FDB_RMIID1_MED")]
	public partial class wfdc_FDB_RMIID1_MED : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _MEDID;
		
		private decimal _ROUTED_DOSAGE_FORM_MED_ID;
		
		private string _MED_STRENGTH;
		
		private string _MED_STRENGTH_UOM;
		
		private string _MED_MEDID_DESC;
		
		private decimal _GCN_SEQNO;
		
		private string _MED_GCNSEQNO_ASSIGN_CD;
		
		private string _MED_NAME_SOURCE_CD;
		
		private string _MED_REF_FED_LEGEND_IND;
		
		private string _MED_REF_DEA_CD;
		
		private string _MED_REF_MULTI_SOURCE_CD;
		
		private string _MED_REF_GEN_DRUG_NAME_CD;
		
		private string _MED_REF_GEN_COMP_PRICE_CD;
		
		private string _MED_REF_GEN_SPREAD_CD;
		
		private string _MED_REF_INNOV_IND;
		
		private string _MED_REF_GEN_THERA_EQU_CD;
		
		private string _MED_REF_DESI_IND;
		
		private string _MED_REF_DESI2_IND;
		
		private string _MED_STATUS_CD;
		
		private System.Nullable<decimal> _GENERIC_MEDID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMEDIDChanging(decimal value);
    partial void OnMEDIDChanged();
    partial void OnROUTED_DOSAGE_FORM_MED_IDChanging(decimal value);
    partial void OnROUTED_DOSAGE_FORM_MED_IDChanged();
    partial void OnMED_STRENGTHChanging(string value);
    partial void OnMED_STRENGTHChanged();
    partial void OnMED_STRENGTH_UOMChanging(string value);
    partial void OnMED_STRENGTH_UOMChanged();
    partial void OnMED_MEDID_DESCChanging(string value);
    partial void OnMED_MEDID_DESCChanged();
    partial void OnGCN_SEQNOChanging(decimal value);
    partial void OnGCN_SEQNOChanged();
    partial void OnMED_GCNSEQNO_ASSIGN_CDChanging(string value);
    partial void OnMED_GCNSEQNO_ASSIGN_CDChanged();
    partial void OnMED_NAME_SOURCE_CDChanging(string value);
    partial void OnMED_NAME_SOURCE_CDChanged();
    partial void OnMED_REF_FED_LEGEND_INDChanging(string value);
    partial void OnMED_REF_FED_LEGEND_INDChanged();
    partial void OnMED_REF_DEA_CDChanging(string value);
    partial void OnMED_REF_DEA_CDChanged();
    partial void OnMED_REF_MULTI_SOURCE_CDChanging(string value);
    partial void OnMED_REF_MULTI_SOURCE_CDChanged();
    partial void OnMED_REF_GEN_DRUG_NAME_CDChanging(string value);
    partial void OnMED_REF_GEN_DRUG_NAME_CDChanged();
    partial void OnMED_REF_GEN_COMP_PRICE_CDChanging(string value);
    partial void OnMED_REF_GEN_COMP_PRICE_CDChanged();
    partial void OnMED_REF_GEN_SPREAD_CDChanging(string value);
    partial void OnMED_REF_GEN_SPREAD_CDChanged();
    partial void OnMED_REF_INNOV_INDChanging(string value);
    partial void OnMED_REF_INNOV_INDChanged();
    partial void OnMED_REF_GEN_THERA_EQU_CDChanging(string value);
    partial void OnMED_REF_GEN_THERA_EQU_CDChanged();
    partial void OnMED_REF_DESI_INDChanging(string value);
    partial void OnMED_REF_DESI_INDChanged();
    partial void OnMED_REF_DESI2_INDChanging(string value);
    partial void OnMED_REF_DESI2_INDChanged();
    partial void OnMED_STATUS_CDChanging(string value);
    partial void OnMED_STATUS_CDChanged();
    partial void OnGENERIC_MEDIDChanging(System.Nullable<decimal> value);
    partial void OnGENERIC_MEDIDChanged();
    #endregion
		
		public wfdc_FDB_RMIID1_MED()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEDID", DbType="Decimal(8,0) NOT NULL", IsPrimaryKey=true)]
		public decimal MEDID
		{
			get
			{
				return this._MEDID;
			}
			set
			{
				if ((this._MEDID != value))
				{
					this.OnMEDIDChanging(value);
					this.SendPropertyChanging();
					this._MEDID = value;
					this.SendPropertyChanged("MEDID");
					this.OnMEDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROUTED_DOSAGE_FORM_MED_ID", DbType="Decimal(8,0) NOT NULL")]
		public decimal ROUTED_DOSAGE_FORM_MED_ID
		{
			get
			{
				return this._ROUTED_DOSAGE_FORM_MED_ID;
			}
			set
			{
				if ((this._ROUTED_DOSAGE_FORM_MED_ID != value))
				{
					this.OnROUTED_DOSAGE_FORM_MED_IDChanging(value);
					this.SendPropertyChanging();
					this._ROUTED_DOSAGE_FORM_MED_ID = value;
					this.SendPropertyChanged("ROUTED_DOSAGE_FORM_MED_ID");
					this.OnROUTED_DOSAGE_FORM_MED_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_STRENGTH", DbType="VarChar(15)")]
		public string MED_STRENGTH
		{
			get
			{
				return this._MED_STRENGTH;
			}
			set
			{
				if ((this._MED_STRENGTH != value))
				{
					this.OnMED_STRENGTHChanging(value);
					this.SendPropertyChanging();
					this._MED_STRENGTH = value;
					this.SendPropertyChanged("MED_STRENGTH");
					this.OnMED_STRENGTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_STRENGTH_UOM", DbType="VarChar(15)")]
		public string MED_STRENGTH_UOM
		{
			get
			{
				return this._MED_STRENGTH_UOM;
			}
			set
			{
				if ((this._MED_STRENGTH_UOM != value))
				{
					this.OnMED_STRENGTH_UOMChanging(value);
					this.SendPropertyChanging();
					this._MED_STRENGTH_UOM = value;
					this.SendPropertyChanged("MED_STRENGTH_UOM");
					this.OnMED_STRENGTH_UOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_MEDID_DESC", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string MED_MEDID_DESC
		{
			get
			{
				return this._MED_MEDID_DESC;
			}
			set
			{
				if ((this._MED_MEDID_DESC != value))
				{
					this.OnMED_MEDID_DESCChanging(value);
					this.SendPropertyChanging();
					this._MED_MEDID_DESC = value;
					this.SendPropertyChanged("MED_MEDID_DESC");
					this.OnMED_MEDID_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCN_SEQNO", DbType="Decimal(6,0) NOT NULL")]
		public decimal GCN_SEQNO
		{
			get
			{
				return this._GCN_SEQNO;
			}
			set
			{
				if ((this._GCN_SEQNO != value))
				{
					this.OnGCN_SEQNOChanging(value);
					this.SendPropertyChanging();
					this._GCN_SEQNO = value;
					this.SendPropertyChanged("GCN_SEQNO");
					this.OnGCN_SEQNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_GCNSEQNO_ASSIGN_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_GCNSEQNO_ASSIGN_CD
		{
			get
			{
				return this._MED_GCNSEQNO_ASSIGN_CD;
			}
			set
			{
				if ((this._MED_GCNSEQNO_ASSIGN_CD != value))
				{
					this.OnMED_GCNSEQNO_ASSIGN_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_GCNSEQNO_ASSIGN_CD = value;
					this.SendPropertyChanged("MED_GCNSEQNO_ASSIGN_CD");
					this.OnMED_GCNSEQNO_ASSIGN_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_NAME_SOURCE_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_NAME_SOURCE_CD
		{
			get
			{
				return this._MED_NAME_SOURCE_CD;
			}
			set
			{
				if ((this._MED_NAME_SOURCE_CD != value))
				{
					this.OnMED_NAME_SOURCE_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_NAME_SOURCE_CD = value;
					this.SendPropertyChanged("MED_NAME_SOURCE_CD");
					this.OnMED_NAME_SOURCE_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_FED_LEGEND_IND", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_FED_LEGEND_IND
		{
			get
			{
				return this._MED_REF_FED_LEGEND_IND;
			}
			set
			{
				if ((this._MED_REF_FED_LEGEND_IND != value))
				{
					this.OnMED_REF_FED_LEGEND_INDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_FED_LEGEND_IND = value;
					this.SendPropertyChanged("MED_REF_FED_LEGEND_IND");
					this.OnMED_REF_FED_LEGEND_INDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_DEA_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_DEA_CD
		{
			get
			{
				return this._MED_REF_DEA_CD;
			}
			set
			{
				if ((this._MED_REF_DEA_CD != value))
				{
					this.OnMED_REF_DEA_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_DEA_CD = value;
					this.SendPropertyChanged("MED_REF_DEA_CD");
					this.OnMED_REF_DEA_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_MULTI_SOURCE_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_MULTI_SOURCE_CD
		{
			get
			{
				return this._MED_REF_MULTI_SOURCE_CD;
			}
			set
			{
				if ((this._MED_REF_MULTI_SOURCE_CD != value))
				{
					this.OnMED_REF_MULTI_SOURCE_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_MULTI_SOURCE_CD = value;
					this.SendPropertyChanged("MED_REF_MULTI_SOURCE_CD");
					this.OnMED_REF_MULTI_SOURCE_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_GEN_DRUG_NAME_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_GEN_DRUG_NAME_CD
		{
			get
			{
				return this._MED_REF_GEN_DRUG_NAME_CD;
			}
			set
			{
				if ((this._MED_REF_GEN_DRUG_NAME_CD != value))
				{
					this.OnMED_REF_GEN_DRUG_NAME_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_GEN_DRUG_NAME_CD = value;
					this.SendPropertyChanged("MED_REF_GEN_DRUG_NAME_CD");
					this.OnMED_REF_GEN_DRUG_NAME_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_GEN_COMP_PRICE_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_GEN_COMP_PRICE_CD
		{
			get
			{
				return this._MED_REF_GEN_COMP_PRICE_CD;
			}
			set
			{
				if ((this._MED_REF_GEN_COMP_PRICE_CD != value))
				{
					this.OnMED_REF_GEN_COMP_PRICE_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_GEN_COMP_PRICE_CD = value;
					this.SendPropertyChanged("MED_REF_GEN_COMP_PRICE_CD");
					this.OnMED_REF_GEN_COMP_PRICE_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_GEN_SPREAD_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_GEN_SPREAD_CD
		{
			get
			{
				return this._MED_REF_GEN_SPREAD_CD;
			}
			set
			{
				if ((this._MED_REF_GEN_SPREAD_CD != value))
				{
					this.OnMED_REF_GEN_SPREAD_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_GEN_SPREAD_CD = value;
					this.SendPropertyChanged("MED_REF_GEN_SPREAD_CD");
					this.OnMED_REF_GEN_SPREAD_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_INNOV_IND", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_INNOV_IND
		{
			get
			{
				return this._MED_REF_INNOV_IND;
			}
			set
			{
				if ((this._MED_REF_INNOV_IND != value))
				{
					this.OnMED_REF_INNOV_INDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_INNOV_IND = value;
					this.SendPropertyChanged("MED_REF_INNOV_IND");
					this.OnMED_REF_INNOV_INDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_GEN_THERA_EQU_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_GEN_THERA_EQU_CD
		{
			get
			{
				return this._MED_REF_GEN_THERA_EQU_CD;
			}
			set
			{
				if ((this._MED_REF_GEN_THERA_EQU_CD != value))
				{
					this.OnMED_REF_GEN_THERA_EQU_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_GEN_THERA_EQU_CD = value;
					this.SendPropertyChanged("MED_REF_GEN_THERA_EQU_CD");
					this.OnMED_REF_GEN_THERA_EQU_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_DESI_IND", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_DESI_IND
		{
			get
			{
				return this._MED_REF_DESI_IND;
			}
			set
			{
				if ((this._MED_REF_DESI_IND != value))
				{
					this.OnMED_REF_DESI_INDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_DESI_IND = value;
					this.SendPropertyChanged("MED_REF_DESI_IND");
					this.OnMED_REF_DESI_INDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_REF_DESI2_IND", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_REF_DESI2_IND
		{
			get
			{
				return this._MED_REF_DESI2_IND;
			}
			set
			{
				if ((this._MED_REF_DESI2_IND != value))
				{
					this.OnMED_REF_DESI2_INDChanging(value);
					this.SendPropertyChanging();
					this._MED_REF_DESI2_IND = value;
					this.SendPropertyChanged("MED_REF_DESI2_IND");
					this.OnMED_REF_DESI2_INDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MED_STATUS_CD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string MED_STATUS_CD
		{
			get
			{
				return this._MED_STATUS_CD;
			}
			set
			{
				if ((this._MED_STATUS_CD != value))
				{
					this.OnMED_STATUS_CDChanging(value);
					this.SendPropertyChanging();
					this._MED_STATUS_CD = value;
					this.SendPropertyChanged("MED_STATUS_CD");
					this.OnMED_STATUS_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENERIC_MEDID", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> GENERIC_MEDID
		{
			get
			{
				return this._GENERIC_MEDID;
			}
			set
			{
				if ((this._GENERIC_MEDID != value))
				{
					this.OnGENERIC_MEDIDChanging(value);
					this.SendPropertyChanging();
					this._GENERIC_MEDID = value;
					this.SendPropertyChanged("GENERIC_MEDID");
					this.OnGENERIC_MEDIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
